### ISSUE TITLE
Option to skip

### ISSUE THREAD

**Issue by mike-north** [ember-cli/ember-welcome-page#32]
While I get the value of this addon for new users, it's something every developer has to remove every time they spin up a new project. This has added an extra manual step that wasn't there before, and after the welcome page is seen once or twice, there's a diminishing value for subsequent appearances.

maybe `ember new --skip-welcome` or something, so we can have our cake and eat it too? An environment variable that "bypasses" the welcome page?

**Comment by locks** [comment]
Hey Mike, this should be filed in the [ember-cli](https://github.com/ember-cli/ember-cli) repository instead, as the `new` command and subsequently related options would need to be implemented.

While I understand you wanting to skip it, I worry about the added complexity on CLI's internals for what I view as little gain. It's not necessary for you to remove it, it's an express middleware that does not get added to the build's output so there's no added bloat, and you stop seeing the screen as soon as you create a template, which you probably do quickly after a project creation.

**Comment by mike-north** [comment]
> and you stop seeing the screen as soon as you create a template

I wasn't aware of this. Is this documented somewhere? I've been ripping it out as an extra step every time I create an app to debug addon blueprints

**Comment by stefanpenner** [comment]
@mike-north it would be nice if we can it all in this addon, but do to how parameter parsing works, at least some of the work will likely have to happen in ember-cli.

**Comment by mike-north** [comment]
This is still (as of ember-cli `2.9.0-beta.2`) an early snag whenever I teach a workshop or tutorial. 

A great strength of getting started with ember used to be that you could
* `ember new`
* `cd` into your project
* `ember s`

and you were seeing a working ember app, where what you saw on the screen matched a file you could easily find in your source code.

While I get the intent behind this addon, agree that the problem it's trying to solve is real, and appreciate all of the hard work that @locks has done, it's adding a lot of "magic" (and unfortunately, associated confusion) which may make make it a net loss in terms of ease of getting started.

Here's the progression of thoughts I've seen from people totally new to the framework:
(yes, I've actually stopped multiple students who were confused and asked them to verbalize what they were thinking at each step)

* Ok, looks like the app is working.
* Where is the source code for this page? I want to start tweaking it to see what I can do
* I couldn't find the source code anywhere. Maybe `app/index.html` is pulling something else in from somewhere?
* After studying the "getting started" page more closely, it's telling me to remove something from `package.json`. Odd that I have to start messing with this immediately after starting a project.
* I've just removed it from `package.json` and nothing happened. It's now been 5 minutes into my ember experience and things feel broken and confusing
* **Mike** just told me I have to stop/restart `ember s` in order to pick up on that `package.json` change. Now I see a blank screen
* **Mike** also asked me to run `ember generate template application`. I don't know why I'm running this command because we haven't learned much about ember-cli yet
* **Mike** had me start making some basic HTML in this new `application.hbs` file that was created. Finally I can see the livereload/rebuild loop working in action

This is hurting adoption, and I'm seeing it over and over again across dozens of workshops, tutorials and video courses. Please let me know how I can help get us back to an "easy as 1, 2, 3" starting point.

**Comment by acorncom** [comment]
@mike-north This is something that hasn't fallen off the radar on our end, just hasn't been top priority for the core team with the Glimmer push.  My understanding is it's being discussed at the core team meeting again tomorrow.  Will keep you posted when there is something to say ;-0

**Comment by mike-north** [comment]
Glad to know that this is still on the radar. Just taught another 60 developers how to get started with ember, and this was a confusing snag yet again. Teaching would be way easier if we had  `application.hbs` back.

**Comment by ldong** [comment]
FYI, during 2.14 release:

> A flag --no-welcome has been added for ember new and ember init. Use this flag to skip the inclusion of ember-welcome-page as a dependency in newly created projects.

https://www.emberjs.com/blog/2017/07/06/ember-2-14-released.html

`ember new my-project --no-welcome`
>   --welcome (Boolean) (Default: true) Installs and uses {{ember-welcome-page}}. Use --no-welcome to skip it.

**Comment by Miladinho** [comment]
@mike-north 
@Idong

Thank you for pushing for this, as a new user in fall of 2016 when I learned Ember in school, this issue gave me a huge headache, I was a CS student and I needed to see where the code is and what was going on (where files are, how they are linking and set etc.) The javascript world is so confusing already, so many add-ons, frameworks blah blah blah... it is already not a friendly environment for beginners. Had I stumbled across this earlier I would have saved a lot of time on my final exams. Now that I am building my second ember app I've just spent the first hour figuring this issue out. I was about to dump ember all together and move on.

Important lesson here @acorncom for the Ember team, seriously think about new user adoption and some basic product management. You have a good framework in a messy (Javascript) space so users need to be babied through some of the steps in order to truly appreciate what you've accomplished.

**Comment by sheriffderek** [comment]
Since it's 2019 - and Octane is almost here, It seems like a good time to address this again.

If it's your first time using Ember / and you are getting your command from a place like this:
<img width="400" alt="screen shot 2019-02-23 at 9 05 39 pm" src="https://user-images.githubusercontent.com/2066617/53295372-d3dfaf80-37ae-11e9-922b-3a4798c70d91.png">

Maybe it's a chance to opt in - instead of opt out.

`ember new app-name --welcome` could _add_ the welcome-page instead of a default.

You know that if the person is getting their command from a 'new users' type portal / so, you can control that flow.
